# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CreditCard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CreditCard

  pod 'Swinject'

  target 'CreditCardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CreditCardUITests' do
    # Pods for testing
  end

end
